import { Circuit } from "@tscircuit/core"
import type { AnyCircuitElement } from "circuit-json"
import { Am62lLpddr4Circuit } from "../examples/am62l/am62l-circuit"

const circuit = new Circuit()
circuit.add(Am62lLpddr4Circuit())
await circuit.renderUntilSettled()

const circuitJson = circuit.getCircuitJson()
const breakoutPoints = circuitJson.filter(
  (element) => element.type === "pcb_breakout_point",
)
const sourceTraceIds = new Set(
  breakoutPoints.flatMap((point) => point.source_trace_id ?? []),
)
const sourcePortIds = new Set(
  breakoutPoints.flatMap((point) => point.source_port_id ?? []),
)
const pcbGroupIds = new Set(breakoutPoints.map((point) => point.pcb_group_id))
const pcbPorts = circuitJson.filter(
  (element) =>
    element.type === "pcb_port" && sourcePortIds.has(element.source_port_id),
)
const pcbComponentIds = new Set(
  pcbPorts.flatMap((port) => port.pcb_component_id ?? []),
)

const compactCircuitJson = circuitJson.filter((element) => {
  switch (element.type) {
    case "pcb_board":
      return true
    case "pcb_group":
      return pcbGroupIds.has(element.pcb_group_id)
    case "pcb_component":
      return pcbComponentIds.has(element.pcb_component_id)
    case "pcb_port":
      return sourcePortIds.has(element.source_port_id)
    case "pcb_breakout_point":
      return sourceTraceIds.has(element.source_trace_id ?? "")
    case "source_trace":
      return sourceTraceIds.has(element.source_trace_id)
    default:
      return false
  }
}) satisfies AnyCircuitElement[]

const counts = Object.fromEntries(
  [
    "pcb_board",
    "pcb_group",
    "pcb_component",
    "pcb_port",
    "pcb_breakout_point",
    "source_trace",
  ].map((type) => [
    type,
    compactCircuitJson.filter((element) => element.type === type).length,
  ]),
)

if (
  counts.pcb_board !== 1 ||
  counts.pcb_group !== 2 ||
  counts.pcb_component !== 2 ||
  counts.pcb_port !== 66 ||
  counts.pcb_breakout_point !== 66 ||
  counts.source_trace !== 33
) {
  throw new Error(
    `Unexpected AM62L Circuit JSON shape: ${JSON.stringify(counts)}`,
  )
}

const generatedSource = `// Generated by \`bun run generate:am62l-circuit-json\`. Do not edit manually.
import type { CircuitJson } from "circuit-json"

export const AM62L_CIRCUIT_JSON = ${JSON.stringify(compactCircuitJson, null, 2)} as CircuitJson
`
const outputUrl = new URL(
  "../examples/am62l/am62l-circuit-json.generated.ts",
  import.meta.url,
)
await Bun.write(outputUrl, generatedSource)

console.log(
  `Generated ${compactCircuitJson.length} AM62L Circuit JSON elements (${generatedSource.length} bytes)`,
)
