import { Circuit } from "@tscircuit/core"
import type { AnyCircuitElement, PcbComponent, PcbGroup } from "circuit-json"
import { Am62lLpddr4ThreeMillimeterPaddingCircuit } from "../examples/padding/am62l-lpddr4-three-mm-circuit"

const circuit = new Circuit()
circuit.add(Am62lLpddr4ThreeMillimeterPaddingCircuit())
await circuit.renderUntilSettled()

const autoroutingErrors = circuit.db.pcb_autorouting_error.list()
if (autoroutingErrors.length > 0) {
  throw new Error(
    `AM62L padding fanout failed: ${autoroutingErrors
      .map((error) => error.message)
      .join("; ")}`,
  )
}

const circuitJson = circuit.getCircuitJson()
const breakoutPoints = circuitJson.filter(
  (element) => element.type === "pcb_breakout_point",
)
const sourceTraceIds = new Set(
  breakoutPoints.flatMap((point) => point.source_trace_id ?? []),
)
const sourcePortIds = new Set(
  breakoutPoints.flatMap((point) => point.source_port_id ?? []),
)
const pcbGroupIds = new Set(breakoutPoints.map((point) => point.pcb_group_id))
const pcbPorts = circuitJson.filter(
  (element) =>
    element.type === "pcb_port" && sourcePortIds.has(element.source_port_id),
)
const pcbComponentIds = new Set(
  pcbPorts.flatMap((port) => port.pcb_component_id ?? []),
)

const compactCircuitJson = circuitJson.filter((element) => {
  switch (element.type) {
    case "pcb_board":
      return true
    case "pcb_group":
      return pcbGroupIds.has(element.pcb_group_id)
    case "pcb_component":
      return pcbComponentIds.has(element.pcb_component_id)
    case "pcb_port":
      return sourcePortIds.has(element.source_port_id)
    case "pcb_breakout_point":
      return sourceTraceIds.has(element.source_trace_id ?? "")
    case "source_trace":
      return sourceTraceIds.has(element.source_trace_id)
    default:
      return false
  }
}) satisfies AnyCircuitElement[]

const counts = Object.fromEntries(
  [
    "pcb_board",
    "pcb_group",
    "pcb_component",
    "pcb_port",
    "pcb_breakout_point",
    "source_trace",
  ].map((type) => [
    type,
    compactCircuitJson.filter((element) => element.type === type).length,
  ]),
)

if (
  counts.pcb_board !== 1 ||
  counts.pcb_group !== 2 ||
  counts.pcb_component !== 2 ||
  counts.pcb_port !== 4 ||
  counts.pcb_breakout_point !== 4 ||
  counts.source_trace !== 2
) {
  throw new Error(
    `Unexpected AM62L padding Circuit JSON shape: ${JSON.stringify(counts)}`,
  )
}

const groups = compactCircuitJson.filter(
  (element): element is PcbGroup => element.type === "pcb_group",
)
const components = compactCircuitJson.filter(
  (element): element is PcbComponent => element.type === "pcb_component",
)
for (const group of groups) {
  const component = components.find(
    (candidate) => candidate.pcb_group_id === group.pcb_group_id,
  )
  if (!component || !group.width || !group.height) {
    throw new Error(`Missing geometry for padding group ${group.name}`)
  }
  const horizontalPadding = (group.width - component.width) / 2
  const verticalPadding = (group.height - component.height) / 2
  if (
    Math.abs(horizontalPadding - 3) > 1e-6 ||
    Math.abs(verticalPadding - 3) > 1e-6
  ) {
    throw new Error(
      `${group.name} does not preserve 3mm padding: horizontal=${horizontalPadding}, vertical=${verticalPadding}`,
    )
  }
}

const generatedSource = `// Generated by \`bun run generate:padding-circuit-json\`. Do not edit manually.
import type { CircuitJson } from "circuit-json"

export const AM62L_LPDDR4_THREE_MM_CIRCUIT_JSON = ${JSON.stringify(compactCircuitJson, null, 2)} as CircuitJson
`
const outputUrl = new URL(
  "../examples/padding/am62l-lpddr4-three-mm-circuit-json.generated.ts",
  import.meta.url,
)
await Bun.write(outputUrl, generatedSource)

console.log(
  `Generated ${compactCircuitJson.length} AM62L padding Circuit JSON elements (${generatedSource.length} bytes)`,
)
